db:
  ip: 127.0.0.1
server:
  port: 8080

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: html
    encoding: UTF-8
  jpa:
    database: MySQL
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456


mybatis:
  #实体类所做包
  type-aliases-package: com.back.entity
  #mappers.xml所在位置
  mapper-locations: classpath:mappers/*.xml

