db:
  ip: 127.0.0.1
server:
  port: 8888

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: html
    encoding: UTF-8
  jpa:
    database: MySQL
    show-sql: true

